@startuml
package Droidi{
abstract class droide{
    -modello : String
    -altezza : String
    -ID : String
    +{abstract}attivaDisattiva() : boolean
    +{abstract}assembla() : void
}

class droidePattuglia{
    +pianificaItinerario() : String
    +attivaDisattiva() : boolean
    +assembla() : void
}

class droideRiparatore{
    +ripara(d : Droide) : Droide
    +attivaDisattiva() : boolean
    +assembla() : void
}
}
package fabbrica{
class gruppoManutenzione{
    -nome : String
    -listaDroidi : droideRiparatore[]
    +rilasciaDroide(ID : String) : droideRiparatore
    +addDroide(d : droideRiparatore) : void
    +removeDroide(index : int) : void
}

class catenaProduzione{
    -nome : String
    -gruppoManutenzione : ArrayList<droideRiparatore>
    +creaDroide(modello : String, altezza : String, ID : String) : Droide
    +addDroide(d : droideRiparatore) : void
    +removeDroide(index : int) : void
}
class Fabbrica{
    -nome : String
    -listaCateneProd : listaCateneProd[]
    -listaGruppiManut : ArrayList<gruppoManutenzione>

}

}
droide <|-- droidePattuglia
droide <|-- droideRiparatore

Fabbrica *-- gruppoManutenzione
gruppoManutenzione *-- catenaProduzione

gruppoManutenzione o-- droideRiparatore

catenaProduzione ..> droide

@enduml