@startuml
@startuml

class Cliente {
    -nome : String
    -indirizzo : String
}

class droide{
    -modello : String
}

class umano{
    -eta : int
}

class Vip{
    -bonus : double
}

class Contratto{
    -ID : String
    -dataI : String
    -dataF : String
    -importo : double
    -cliente : cliente
    -testo : String
    -listaPolizze : Arraylist<Polizza>
    +addPolizza(p : Polizza) : void
    +removePolizza(index : int) : void
}
class agenzia{
    -nome : String
    +listaPolizze : Arraylist<Polizza>
    -listaContratti : Arraylist<Contratto>
    -listaClienti : Arraylist<Cliente>
    +contrattoValido(c : Contratto) : boolean
    +durataContratto(c : Contratto) : String
    +addCliente(c : Cliente) : void
    +removeCliente(index : int) : void
    +addContratto(c : Contratto) : void
    +removeContratto(index : int) : void
    +addPolizza(p : Polizza) : void
    +removePolizza(index : int) : void
}

Exception eccezione

class Polizza{
    -tipo : String
    -testo : String
}

Cliente <|-- droide
Cliente <|-- umano
Cliente <|-- Vip

Polizza "1..*"--o "1"Contratto
Cliente "1..*"--o "1" agenzia
Cliente --> Contratto
Polizza "1..*"--o "1" agenzia
agenzia "1" o-- "1..*" Contratto
@enduml
@enduml