@startuml

class SensoreTemp{
    -stato : boolean

}
class SensosoreMov{
    -stato : boolean

}
class SistemaMonitoraggioTemp{
    -sensoriTemp : SensoreTemp[]
    +eseguiDiagnostica() : boolan

}
class SistemaMonitoraggioMov{
    -sensoriMov : SensosoreMov[]
    +eseguiDiagnostica() : boolan
}

class SistemaMonitoraggio{
    -sysTemp : SistemaMonitoraggioTemp
    -sysMov : SistemaMonitoraggioMov
}
class Prigione {
    - nome: String
    - sistemiMonitoraggio: List<SistemaMonitoraggio>
    + Prigione(nome: String)
    + aggiungiSistema(sistema: SistemaMonitoraggio): void
}
SensoreTemp --* SistemaMonitoraggioTemp
SensosoreMov --* SistemaMonitoraggioMov
SistemaMonitoraggioMov --* SistemaMonitoraggio
SistemaMonitoraggioTemp --* SistemaMonitoraggio
Prigione --* SistemaMonitoraggio
@enduml