@startuml

:azienda: as az
:responsabileT: as resp
:studente: as stud

(produce offerte tirocinio) as UC1
(accordarsi con azienda) as UC2
(approva offerte) as UC3
(rifiuta offerta) as UC4
(visualizza offerte accettate) as UC5
(assegna tirocinio) as UC6
(approva accoppiamento studente-tirocinio) as UC7
(rifiuta accoppiamento studente-tirocinio) as UC8
(stampa accordo) as UC9
(notifica azienda) as UC10

az --> UC1
resp --> UC3
resp --> UC4
UC4 .> UC10 : <<extend>>
stud --> UC5
UC5 .> UC2 : <<include>>
az --> UC6
resp --> UC7
UC7 .> UC9 : <<extend>>
resp --> UC8
UC8 ..> UC10 : <<extend>>


@enduml