@startuml
package torreHanoi{

class Torre{
-Arraylist<> pila : T
+push(T elemento) : void
+pop() : T
+top() : T
+isEmpty() : boolean
+size() : int
}

class Colonne{
-torre1 : Torre
-torre2 : Torre
-torre2 : Torre
-inizializzaDischi() : void
+stampaTorri() : void
}
class Disco{
-dimensione : int
}

}

package Main{
class main{
}
}
Colonne --> Main
Torre "3" o.. Colonne
Disco o.. Torre
@enduml