@startuml
    :Consigliere della citta: as CC
    :Capo consigliere: as HeadC
    :Centro operativo di sicurezza: as COS
    :Sistema di intelligence: as SI
    :Sindaco: as SIND
    :Ministero innovazione tecnologica: as MIT
    :Direttore Tecnico: as DIR

    (Inviare comunicazioni di emergenza) as UC1
    (Convocare riunioni) as UC2


    (Convocare riunioni con sindaco) as UC3


    (Monitora la citta in tempo reale) as UC4
    usecase UC5 as "
    Attivare protocollo di difesa
    --
    se minaccia rilevata
    "

    usecase UC6 as "
    Dichiara stato di emergenza
    --
    se autorizzato dal sindaco
    "


    (Gestisce le squadre di manutenzione) as UC7
    (aggiorna software) as UC8
    (Autorizza modifiche di sicurezza del sistema) as UC9

    HeadC --|> CC : <<extend>>
    CC -- UC1
    CC -- UC2
    HeadC --> UC3
    COS -- UC4
    COS -- UC5
    COS -- UC6
    MIT -- UC7
    MIT -- UC8
    DIR -- UC9
    SIND -- UC6
    SIND -- UC3
    SI -- UC5
    UC3 ..> (rilascio permesso speciale) : <<include>>


@enduml