@startuml

''attori politici
:senatore: as sn
:senatore anzino: as HeadSn
(accedere canali di comunicazione) as UC1
(organizzare consigli dei senatori) as UC2
(identificazione) as UC3
(organizza colloqui con imperatore) as UC4
(possesso di permesso speciale) as UC5


''attori militari
:Gran Visir: as GV
:sistema sicurezza planetario: as SSP
(assegna truppe) as UC6
(arresta cittadino) as UC7
(effettua controlli di sicurezza) as UC8


''attori civili
:ministero delle opere imperiali: as MI
(eleggere cariche civili) as UC9
(organizza appalti pubblici) as UC10


sn <|-- HeadSn

sn -- UC1
UC1 ..> UC3 :<<include>>
sn -- UC2
HeadSn -- UC4
UC4 ..> UC5 :<<include>>

GV -- UC6
GV --> UC8
UC8 <.. UC7 :"<<extend>>
SSP -- UC8

MI -- UC9
MI -- UC10

@enduml